wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.2
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.9.6
    start_time: 1643395967
    t:
      1:
      - 1
      3:
      - 4
      - 15
      - 16
      4: 3.9.6
      5: 0.12.2
      8:
      - 5
batch_size:
  desc: null
  value: 2
d_model:
  desc: null
  value: 512
eos_weight:
  desc: null
  value: 0.8
epochs:
  desc: null
  value: 10
lr:
  desc: null
  value: 0.0001
nhead:
  desc: null
  value: 8
num_encoder_layers:
  desc: null
  value: 4
